### ISSUE TITLE
Transitioning Keyers on MiniMEs with a Carbonite

### ISSUE THREAD

**Issue by Shawnteague** [bitfocus/companion-module-rosstalk#14]
I'm trying to set up a button to transition a Background AND Key 1 AND Key 2 on a MiniME but when I try to specify the MiniME as the destination in the "rosstalk: Transition Keyer" MLE field it turns red and won't take the command. Am I doing something wrong here? Screenshot attached for illustration...

![Screen Shot 2020-08-14 at 5 05 15 PM](https://user-images.githubusercontent.com/69701393/90300838-52238c00-de51-11ea-9294-7e8a4d245af5.png)

**Comment by krocheck** [comment]
Yeah, I see why, though I'm not sure why this decision was made.  The "Transition Keyer" MLE field is setup only to accept numbers and is hard coded to `ME:x`.  The other instances, as you've noted, accept the full syntax.  This could be because Acuity doesn't address this command as `ME:1:4`, rather to trans keyer 4 in ME 1 on Acuity it is simply `1:4`.  This is actually true of a lot of the commands since the Acuity doesn't use the bus type prefix selector in a majority of cases.  BUT, that would mean this command doesn't work for Acuity since `ME:` is hard-coded.

This is all a round-about way to say that this is working as intended (integers only), but I believe its reasonable to fix the field to accept the full prefix structure.  I'll add it to my list.

**Comment by famerdave** [comment]
Hello, just figured I'd also mention this. Carbonite Ultra uses ME:PP to represent its MAIN ME, which means this command also doesn't work.... --- I'm planning for a show right now and would like this to be fixed. My work around is using Custom Controls but its a bit clunky.

**Comment by famerdave** [comment]
Turns out, the Carbonite Ultra also accepts ME:0 for the main P/P ME, so that works in this field, but It would be nice to be able to control MiniME keys as well.
