### ISSUE TITLE
Feature Request: Support for internal custom variables

### ISSUE THREAD

**Issue by benturnbull1991** [bitfocus/companion-module-rosstalk#21]
It would be amazing to see support for the internal custom variables in the Ross Video Module. It would massively cut down on the number of buttons and pages needed.

**Comment by DaanCMP** [comment]
Hi, is this feature being worked on?

**Comment by Caleb-Wishart** [comment]
What do you mean by internal custom variables?

Adding your own custom variables in Companion and using that or The state of the ross switcher?

**Comment by benturnbull1991** [comment]
I mean using your own custom variables in Companion with the RossTalk module. 

Eg a (Companion) internal custom variable called “me_dest” that could be “PP:PGM” or “ME1:PGM” could then be used on a button like ME:”$(companioninstance:me_dest)” to easily control different MEs from the same buttons.

This has been implemented very well in the ETC Eos module, and I’m sure many others.

**Comment by Caleb-Wishart** [comment]
When I was updating this module to companion V3 I added support for #23.

It seems like you want to be able to use variables with existing commands instead of having to also know the right commands to send (like AUTOCUT).

I can see if I can change the existing commands to accept variables in the input as I believe it should be a simple internal change.

I'll see if I can reference that other module to ensure it's similar as well.

**Comment by benturnbull1991** [comment]
Yes that’s exactly it. 

Thanks very much for your work on the module.

**Comment by Caleb-Wishart** [comment]
If I get the time to do it you will likely still need to wait for the next major release of companion (v3) as I'm pretty sure they aren't planning on releasing another minor.

And no problem, it's one of the modules that I use so wanted to make sure it was upgraded and thought to do some easy improvements while at it.
